# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web server
    init: python -m http.server 8000 # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

ports:
  - port: 8000
    onOpen: open-preview
